language: node_js
sudo: required
os:
  - linux
node_js:
  - "10.0.0"
script:
- travis_retry npm install --depth 0 --silent
- npm run lint
- npm run build
- travis_retry npm run test:node
- travis_retry npm run test:browser
- npm run test:typings